version: "3.9"

services:
  dust3r_runner:
    build:
      context: ./models/dust3r
    image: dust3r
    volumes:
      - ./data:/workspace/data
      - ./results:/workspace/results
      - ./scripts:/workspace/scripts
    working_dir: /workspace
    entrypoint: ["/bin/bash"]